### ISSUE TITLE
Can't use an undefined value as an ARRAY reference at /usr/local/lib/perl5/5.36.0/Math/BigInt/Calc.pm

### ISSUE THREAD

**Issue by dgofman** [jayendrapatil/kubernetes-exercises#3]
By running an example https://github.com/jayendrapatil/kubernetes-exercises/blob/main/topics/jobs.md

`kubectl create job pi --image=perl -- perl -Mbignum=bpi -wle 'print bpi(2000)'`

on

https://killercoda.com/killer-shell-ckad/scenario/kubectl-contexts

I got an error

**Can't use an undefined value as an ARRAY reference at /usr/local/lib/perl5/5.36.0/Math/BigInt/Calc.pm line 1049.**

Suggest specifying the perl version 5.34.

`kubectl create job pi --image=perl:5.34 -- perl -Mbignum=bpi -wle 'print bpi(2000)'`

**Comment by jayendrapatil** [comment]
Thanks for the feedback, tested it again on killercoda and works fine.
